package com.gazilla.mihail.gazillaj.utils;

import com.gazilla.mihail.gazillaj.R;

public class MenuImg {

    public int getImg(int id){
        switch (id){
            case 1 : return R.drawable.menu_id_1;
            case 2 : return R.drawable.menu_id_2;
            case 3 : return R.drawable.menu_id_3;
            case 4 : return R.drawable.menu_id_4;
            case 5 : return R.drawable.menu_id_5;
            case 6 : return R.drawable.menu_id_6;
            case 7 : return R.drawable.menu_id_7;
            case 8 : return R.drawable.menu_id_8;
            case 9 : return R.drawable.menu_id_9;
            case 10 : return R.drawable.menu_id_10;
            case 11 : return R.drawable.menu_id_11;
            case 12 : return R.drawable.menu_id_12;
            case 13 : return R.drawable.menu_id_13;
            case 14 : return R.drawable.menu_id_14;
            case 15 : return R.drawable.menu_id_15;
            case 16 : return R.drawable.menu_id_16;
            case 17 : return R.drawable.menu_id_17;
            case 18 : return R.drawable.menu_id_18;
            case 19 : return R.drawable.menu_id_19;
            case 20 : return R.drawable.menu_id_20;
            case 21 : return R.drawable.menu_id_21;
            case 22 : return R.drawable.menu_id_22;
            case 23 : return R.drawable.menu_id_23;
            case 24 : return R.drawable.menu_id_24;
            case 25 : return R.drawable.menu_id_25;
            case 26 : return R.drawable.menu_id_26;
            case 27 : return R.drawable.menu_id_27;
            case 28 : return R.drawable.menu_id_28;
            case 29 : return R.drawable.menu_id_29;
            case 30 : return R.drawable.menu_id_30;
            case 31 : return R.drawable.menu_id_31;
            case 32 : return R.drawable.menu_id_32;
            case 33 : return R.drawable.menu_id_33;
            case 34 : return R.drawable.menu_id_34;
            case 35 : return R.drawable.menu_id_35;
            case 36 : return R.drawable.menu_id_36;
            case 37 : return R.drawable.menu_id_37;
            case 38 : return R.drawable.menu_id_38;
            case 39 : return R.drawable.menu_id_39;
            case 40 : return R.drawable.menu_id_40;
            case 41 : return R.drawable.menu_id_41;
            case 42 : return R.drawable.menu_id_42;
            case 43 : return R.drawable.menu_id_43;
            case 44 : return R.drawable.menu_id_44;
            case 45 : return R.drawable.menu_id_45;
            case 46 : return R.drawable.menu_id_46;
            case 47 : return R.drawable.menu_id_47;
            case 48 : return R.drawable.menu_id_48;
            //case 49 : return R.drawable.menu_id_49;
            case 50 : return R.drawable.menu_id_50;
            case 51 : return R.drawable.menu_id_51;
            case 52 : return R.drawable.menu_id_52;
            case 53 : return R.drawable.menu_id_53;
            case 54 : return R.drawable.menu_id_54;
            case 55 : return R.drawable.menu_id_55;
            case 56 : return R.drawable.menu_id_56;
            case 57 : return R.drawable.menu_id_57;
            case 58 : return R.drawable.menu_id_58;
            case 59 : return R.drawable.menu_id_59;
            case 60 : return R.drawable.menu_id_60;
            case 61 : return R.drawable.menu_id_61;
            case 62 : return R.drawable.menu_id_62;
            case 63 : return R.drawable.menu_id_63;
            case 64 : return R.drawable.menu_id_64;
            case 65 : return R.drawable.menu_id_65;
            case 66 : return R.drawable.menu_id_66;
            case 67 : return R.drawable.menu_id_67;
            case 68 : return R.drawable.menu_id_68;
            case 69 : return R.drawable.menu_id_69;
            case 70: return R.drawable.menu_id_70;
            case 71: return R.drawable.menu_id_71;
            case 72: return R.drawable.menu_id_72;
            case 73: return R.drawable.menu_id_73;
            case 74: return R.drawable.menu_id_74;
            case 75: return R.drawable.menu_id_75;
            case 76: return R.drawable.menu_id_76;
            case 77: return R.drawable.menu_id_77;
            case 78: return R.drawable.menu_id_78;
            case 79: return R.drawable.menu_id_79;
            case 80: return R.drawable.menu_id_80;
            case 81: return R.drawable.menu_id_81;
            case 82: return R.drawable.menu_id_82;
            case 83: return R.drawable.menu_id_83;
            case 84: return R.drawable.menu_id_84;
            case 85: return R.drawable.menu_id_85;
            case 86: return R.drawable.menu_id_86;
            case 87: return R.drawable.menu_id_87;
            case 88: return R.drawable.menu_id_88;
            case 89: return R.drawable.menu_id_89;
            case 90: return R.drawable.menu_id_90;
            case 91: return R.drawable.menu_id_91;
            case 92: return R.drawable.menu_id_92;
            //case 93: return R.drawable.menu_id_93;
            //case 94: return R.drawable.menu_id_94;
            //case 95: return R.drawable.menu_id_95;
            //case 96: return R.drawable.menu_id_96;
            //case 97: return R.drawable.menu_id_97;
            //case 98: return R.drawable.menu_id_98;
            //case 99: return R.drawable.menu_id_99;
            //case 100: return R.drawable.menu_id_100;
            //case 101: return R.drawable.menu_id_101;
            //case 102: return R.drawable.menu_id_102;
            //case 103: return R.drawable.menu_id_103;
            //case 104: return R.drawable.menu_id_104;
            //case 105: return R.drawable.menu_id_105;
            //case 106: return R.drawable.menu_id_106;
            //case 107: return R.drawable.menu_id_107;
            //case 108: return R.drawable.menu_id_108;
            //case 109: return R.drawable.menu_id_109;
            //case 110: return R.drawable.menu_id_110;
            //case 111: return R.drawable.menu_id_111;
            //case 112: return R.drawable.menu_id_112;
            //case 113: return R.drawable.menu_id_113;
            //case 114: return R.drawable.menu_id_114;
            //case 115: return R.drawable.menu_id_115;
            //case 116: return R.drawable.menu_id_116;
            //case 117: return R.drawable.menu_id_117;
            //case 118: return R.drawable.menu_id_118;
            //case 119: return R.drawable.menu_id_119;
            //case 120: return R.drawable.menu_id_120;



        }
        return 0;
    }
}
